sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Createing an image with dockefile"
  - docker build -t markcha/react_nginx -f Dockerfile.dev .
script:
  - docker run -e CI=true markcha/react_nginx npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-west-2-152670176028"
  bucket_path: "docker-react-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY