sudo: required

language: generic

services:
  - docker

before_install:
	- echo "start Createing an image with dockefile"
	- docker build -t markcha/react -f Dockerfile.dev ./
script:
	- docker run -e CI=true markcha/react npm run test -- --converage

after_success:
	- echo "Test Success" 